# syntax=docker/dockerfile:1
# Jupyter with Java 11 baked in
FROM jupyter/scipy-notebook:python-3.11
USER root
RUN apt-get update -y \
 && apt-get install -y --no-install-recommends openjdk-11-jre-headless \
 && apt-get clean && rm -rf /var/lib/apt/lists/*
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
ENV PATH="$JAVA_HOME/bin:$PATH"
USER ${NB_UID}
